# -*- coding: utf-8 -*-
"""Instrumentacao_parte1_1ordem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hzM3vNtKYipOY6x7bcKZeIzkUzRo025b
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

path = "/content/dados1ordem.xlsx"
data_1ordem = pd.read_excel(path, sheet_name="Plan1")
data_1ordem.columns = ["Tempo","Lento","Rapido"]
data_1ordem.head()

plt.figure(figsize=(16,8))
plt.plot(data_1ordem["Tempo"],data_1ordem["Lento"])
plt.title("Resposta Lenta")
plt.grid()
plt.show()

diff_lento = np.diff(data_1ordem["Lento"])/np.diff(data_1ordem["Tempo"])
plt.figure(figsize=(16,8))
plt.plot(data_1ordem["Tempo"][:50],diff_lento)
plt.title("Sensibilidade Lenta")
plt.grid()
plt.show()

K = 1

plt.figure(figsize=(16,8))
plt.plot(data_1ordem["Tempo"],np.log(1-(K*(data_1ordem["Lento"]))))
plt.title("Z em função do tempo, para K={}".format(K))
plt.grid()
plt.show()

Tal_lento = round(((-1/(np.diff(np.log(1-(K*(data_1ordem["Lento"]))))/np.diff(data_1ordem["Tempo"])))).mean(),2)
print(Tal_lento)

"""#Sistema Rápido

"""

plt.figure(figsize=(16,8))
plt.plot(data_1ordem["Tempo"],data_1ordem["Rapido"])
plt.title("Resposta Rápida")
plt.grid()
plt.show()

diff_lento = np.diff(data_1ordem["Rapido"])/np.diff(data_1ordem["Tempo"])
plt.figure(figsize=(16,8))
plt.plot(data_1ordem["Tempo"][:50],diff_lento)
plt.title("Sensibilidade Rapida")
plt.grid()
plt.show()

K = 1

plt.figure(figsize=(16,8))
plt.plot(data_1ordem["Tempo"],np.log(1-(K*(data_1ordem["Rapido"]))))
plt.title("Z em função do tempo, para K={}".format(K))
plt.grid()
plt.show()

Tal_rapido = round(((-1/(np.diff(np.log(1-(K*(data_1ordem["Rapido"]))))/np.diff(data_1ordem["Tempo"])))).mean(),2)
print(Tal_rapido)

